DELETE DISTRIBUICAO.PECA WHERE SEQ_PROCESSO = 9002;

DELETE DISTRIBUICAO.PROCESSO WHERE SEQ_PROCESSO = 9002;

DELETE DISTRIBUICAO.DISTRIBUICAO WHERE SEQ_DISTRIBUICAO = 9003;

DELETE DISTRIBUICAO.FILA_DISTRIBUICAO WHERE SEQ_DISTRIBUICAO = 9003;