# Define a configuração para rodar os testes e2e
# As variáveis utilizadas neste arquivo estão definidas no arquivo .env
version: '2'
services:
  discovery:
    ports:
     - "8761:8761"
    environment:
     - JAVA_OPTS=${JAVA_SERVICE_OPTS}
  gateway:
    ports:
     - "8765:8765"
  services:
    environment:
     - spring.profiles.active=${JAVA_SERVICE_SPRING_PROFILES}
     - JAVA_OPTS=${JAVA_SERVICE_OPTS}
  distribuicao:
    container_name: distribuicao
    image: stfdigital-autuacao-distribuicao
    environment:
     - JAVA_OPTS=${JAVA_SERVICE_OPTS}
     - spring.profiles.active=${JAVA_SERVICE_SPRING_PROFILES},e2e
    depends_on:
     - rabbit
     - discovery
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:2.53.0
    ports:
     - "4444:4444"
    depends_on:
     - docker
  docker:
    container_name: docker-ambassador
    image: svendowideit/ambassador
    environment:
     - UI_PORT_8443_TCP=tcp://ui:8443
     - GATEWAY_PORT_8765_TCP=tcp://gateway:8765
    depends_on:
     - ui
     - gateway