version: '2'
services:
  rabbit:
    image: rabbitmq:management
    ports:
     - "15672:15672"
  discovery:
    image: discovery
    ports:
     - "8761:8761"
  gateway:
    image: gateway
    ports:
     - "8765:8765"
  servicos:
    image: services
    ports:
     - "8081:8081"
     - "8281:8181"
    environment:
     - spring.profiles.active=development
     - JAVA_OPTS=-Xdebug, -Xrunjdwp:server=y,transport=dt_socket,suspend=n