# Define a configuração para rodar esse contexto construído localmente
version: '2'
services:
  distribuicao:
    extends:
      file: shared/compose/common.yml
      service: distribuicao
    image: stfdigital-autuacao-distribuicao
    depends_on:
     - rabbit
     - discovery
